[runtime] Rework how we call 'ConformsToProtocol' a little bit.
Use the GCHandle stored on the native instance to find the managed instance to
call 'ConformsToProtocol' on, instead of looking up the native handle in our
object dictionary.

Hopefully fixes this random exception:

    ObjCRuntime.RuntimeException: Failed to marshal the Objective-C object 0x13d566800 (type: MyType). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'MyType' does not have a constructor that takes one NativeHandle argument).
       at ObjCRuntime.Runtime.MissingCtor(IntPtr , IntPtr , Type , MissingCtorResolution , IntPtr , RuntimeMethodHandle )
       at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr , Type , MissingCtorResolution , IntPtr , RuntimeMethodHandle )
       at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr , Type , MissingCtorResolution )
       at ObjCRuntime.Runtime.ConstructNSObject(IntPtr , IntPtr , MissingCtorResolution )
       at ObjCRuntime.Runtime.GetNSObject(IntPtr , MissingCtorResolution , Boolean )
       at ObjCRuntime.Runtime.GetNSObject(IntPtr )
       at ObjCRuntime.Runtime.InvokeConformsToProtocol(IntPtr , IntPtr )
       at ObjCRuntime.Runtime.invoke_conforms_to_protocol(IntPtr obj, IntPtr protocol, IntPtr* exception_gchandle)
       Exception_EndOfInnerExceptionStack

Might fix the following issues:

* https://github.com/dotnet/macios/issues/21648
* https://github.com/dotnet/maui/issues/28261